stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion
  
  prepare_base_model:
    cmd: python src/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/components/prepare_base_model.py
      - config/config.yaml

    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    
    outs:
      - artifacts/base_model
  

  training:
    cmd: python src/pipeline/stage_03_model_training.py
    deps:
      - src/components/model_trainer.py
      - src/components/prepare_callback.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/base_model

    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    
    outs:
      - artifacts/training
  

  evaluation:
    cmd: python src/pipeline/stage_04_model_evaluation.py
    deps:
      - src/components/model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training

    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    
    metrics:
    - scores.json:
        cache: false
      
  

